### ISSUE TITLE
`signal_graceful_exit` just set a flag for graceful exit?

### ISSUE THREAD

**Issue by spacewander** [openresty/lua-resty-core#112]
It seems that `signal_graceful_exit` only set the `ngx_quit` instead of triggering a real graceful exit...

Refer from the Nginx source:
```
sigsuspend(&set);
...
if (ngx_quit) {
```

I guess that if a graceful exit is in need, it is required to send a signal to resume master process after `sigsuspend`.

Maybe I am missing something.

**Comment by agentzh** [comment]
@spacewander It only works for the *current* nginx process, as stated in the nginx documentation. A worker can not usually send a signal to master, for example, since a worker usually does not have enough permissions to do so. This feature is mostly for an nginx worker to voluntarily gracefully shut down itself.

**Comment by agentzh** [comment]
@spacewander If you want to send signals to nginx master from within the same nginx daemon, then you should use the new "privileged agent" process feature instead in OpenResty:

https://github.com/openresty/lua-resty-core/blob/master/lib/ngx/process.md#enable_privileged_agent
