### ISSUE TITLE
nginx/lua-nginx-module/lua-resty-core compatibility matrix

### ISSUE THREAD

**Issue by Hsn723** [openresty/lua-resty-core#286]
The [Nginx compatibility](https://github.com/openresty/lua-nginx-module#nginx-compatibility) section in lua-nginx-module indicates support for 1.17.x, however the [Prerequisites](https://github.com/openresty/lua-resty-core#prerequisites) section of lua-resty-core warns about potential compatibility issues if using incompatible library versions. Currently OpenResty is at Nginx core 1.15.x, and we'd like to use 1.17.x by building it with lua-nginx-module and lua-resty-core since starting with lua-nginx-module v0.10.16 lua-resty-core will apparently be mandatory.

Would it be possible to have some compatibility matrix between nginx, lua-nginx-module and lua-resty-core for people looking into building the latest themselves? Preferably stable versions.

**Comment by agentzh** [comment]
@Hsn723 We cannot do the full matrix since we cannot test the matrix ourselves. It's just too big. We already have a big test matrix which takes huge amount of computing resources and time:

http://qa.openresty.org/

We highly recommend using our OpenResty releases. That's the only thing we test thoroughly and support fully. Other combinations are mostly at the user's own risk. And this is actually the whole point of OpenResty releases anyway. To solve the compatibility pain among so many components and libraries, at least to a good enough extend. Similarly, if one really wants to build their own Nginx, then they should look at the version combinations for those components in those OpenResty releases.

**Comment by agentzh** [comment]
BTW, OpenResty 1.17.8.1 RC1 is around the corner with the latest Nginx 1.17.8 core. We already pushed out a preview version for it:

https://openresty.org/download/openresty-1.17.8.1rc0.tar.gz

**Comment by Hsn723** [comment]
Thanks, although the https://qa.openresty.org/ page only shows 1.15.8? I am aware of 1.17.8.1 RC1 however we'd like to avoid waiting for OpenResty to catch up with Nginx core, so that we can apply any emergency fixes as needed. A simple list of known working combinations or the 1.17.x results for the above website would have be appreciated.

**Comment by agentzh** [comment]
We only publish good enough test reports to that site. We're still working on the 1.17.8.1 version. The best we have right now is

https://openresty.org/download/openresty-1.17.8.1rc0.tar.gz
