### ISSUE TITLE
error 'not a semaphore instance' when semaphore.post

### ISSUE THREAD

**Issue by Will-luffy** [openresty/lua-resty-core#49]
the code like below:
sema.lua
```
local _M = {}

local semaphore = require("ngx.semaphore")

_M.sema = semaphore.new(1)

return _M
```
core.lua
```
local ok, err = sema:wait(0.01)
    if not ok then
        -- lock failed acquired
        -- but go on. This action just set a fence for all but this request
    end
    local ups = upstreamCache:getUpstream(runtime, userInfo)
    if ups ~= nil then
    	if ok then upsSema.post(1) end
        return ups, info
    end
```
I really want to know when the error will occur, thanks

**Comment by agentzh** [comment]
@Will-luffy Two problems that I can see from your code snippet:

1. You never initialize the Lua variable `upsSema`.
2. Use a colon (`:`) to call the `post` method instead of a dot (`.`). They are completely different. Basically, `obj:meth()` is equivalent to `obj.meth(obj)`. Consult the Lua 5.1 reference manual for more details about the Lua method calling syntax.

**Comment by Will-luffy** [comment]
@agentzh thank you very much, I'm so careless that didn't find the problem, I call the `post` with `:` and solve the problem
